version: '3'

services:
  client:
    build: ./client
    container_name: client
    working_dir: /home/node/app
    volumes:
      - ./client:/home/node/app
    ports:
      - 8081:8080
    command: 'yarn serve'
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8082:8080
    depends_on:
      - db
  db:
    image: postgres:11
    container_name: postgres_db
    ports:
      - 8083:5432
    volumes:
      - ./docker/data/:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: root
